name: Publish @teolin/mcp-local-mysql

on:
  workflow_dispatch:

jobs:
  publish:
    uses: ./.github/workflows/publish-mcp.yml
    secrets: inherit
    with:
      package_path: mcps/MySQL
      package_name: "@teolin/mcp-local-mysql"
