name: Publish @teolin/mcp-cloudwatch-logs

on:
  workflow_dispatch:

jobs:
  publish:
    uses: ./.github/workflows/publish-mcp.yml
    secrets: inherit
    with:
      package_path: mcps/CloudWatch
      package_name: "@teolin/mcp-cloudwatch-logs"
