name: Publish @teolin/mcp-github

on:
  workflow_dispatch:

jobs:
  publish:
    uses: ./.github/workflows/publish-mcp.yml
    secrets: inherit
    with:
      package_path: mcps/GitHub
      package_name: "@teolin/mcp-github"
