name: Publish @teolin/mcp-jira

on:
  workflow_dispatch:

jobs:
  publish:
    uses: ./.github/workflows/publish-mcp.yml
    secrets: inherit
    with:
      package_path: mcps/Jira
      package_name: "@teolin/mcp-jira"
