name: Publish kafdrop-mcp-server

on:
  workflow_dispatch:

jobs:
  publish:
    uses: ./.github/workflows/publish-mcp.yml
    secrets: inherit
    with:
      package_path: mcps/Kafdrop
      package_name: kafdrop-mcp-server
