name: Publish @teolin/mcp-azure-ad

on:
  workflow_dispatch:

jobs:
  publish:
    uses: ./.github/workflows/publish-mcp.yml
    secrets: inherit
    with:
      package_path: mcps/AzureAD
      package_name: "@teolin/mcp-azure-ad"
